# Generated by Django 6.0.4 on 2026-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='modo_preparo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='rendimento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
