# Generated by Django 6.0.4 on 2026-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_fichatecnica_modo_preparo_fichatecnica_rendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
