# Generated by Django 6.0.4 on 2026-05-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_fichatecnica_custo_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichatecnica',
            options={'verbose_name': 'Ficha Técnica', 'verbose_name_plural': 'Fichas Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='ingredientefichatecnica',
            options={'verbose_name': 'Ingrediente da Ficha Técnica', 'verbose_name_plural': 'Ingredientes das Fichas Técnicas'},
        ),
        migrations.RenameField(
            model_name='ingredientefichatecnica',
            old_name='custo',
            new_name='preco_unitario',
        ),
    ]
