# Generated by Django 6.0.4 on 2026-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('energia_kcal', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('carboidratos', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('acucares_totais', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('acucares_adicionados', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('gorduras_totais', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('gorduras_saturadas', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('gorduras_trans', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fibra_alimentar', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_medida', models.CharField(blank=True, choices=[('g', 'gramas'), ('kg', 'quilograma'), ('ml', 'mililitro'), ('l', 'litro'), ('un', 'unidade')], max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'db_table': 'Alimento',
                'ordering': ['numero', 'descricao'],
            },
        ),
    ]
