# Generated by Django 6.0.4 on 2026-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('umidade', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('energia_kcal', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('proteina', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('lipideos', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('carboidrato', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fibra_alimentar', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('saturados', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('AG18_1t', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('AG18_2t', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
