# Generated by Django 6.0.4 on 2026-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ['numero', 'descricao'], 'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelTable(
            name='alimento',
            table='Alimento',
        ),
    ]
