# Generated by Django 6.0.4 on 2026-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('g', 'gramas'), ('kg', 'quilograma'), ('ml', 'mililitro'), ('l', 'litro'), ('un', 'unidade')], max_length=10, null=True),
        ),
    ]
