# Generated by Django 6.0.4 on 2026-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_alter_alimento_options_alter_alimento_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='AG18_1t',
            new_name='acucares_adicionados',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='carboidrato',
            new_name='carboidratos',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='saturados',
            new_name='gorduras_saturadas',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='lipideos',
            new_name='gorduras_totais',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='AG18_2t',
            new_name='gorduras_trans',
        ),
        migrations.RenameField(
            model_name='alimento',
            old_name='proteina',
            new_name='proteinas',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='umidade',
        ),
        migrations.AddField(
            model_name='alimento',
            name='acucares_totais',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
