# Generated by Django 5.2.7 on 2026-06-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personalizado', models.CharField(blank=True, max_length=255)),
                ('porcao', models.CharField(default='100g', max_length=50)),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('tamanho_etiqueta', models.CharField(default='medio', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personalizado', models.CharField(blank=True, max_length=255)),
                ('tamanho_porcao', models.CharField(default='100g', max_length=50)),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('mostrar_sodio', models.BooleanField(default=True)),
                ('mostrar_acucar', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('rendimento', models.FloatField(blank=True, null=True)),
                ('modo_preparo', models.TextField(blank=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='IngredienteFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=50)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ingrediente da Ficha Técnica',
                'verbose_name_plural': 'Ingredientes das Fichas Técnicas',
            },
        ),
    ]
