# Generated by Django 6.0.4 on 2026-05-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '__first__'),
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredientefichatecnica',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento'),
        ),
        migrations.AddField(
            model_name='ingredientefichatecnica',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.fichatecnica'),
        ),
    ]
