# Generated by Django 5.2.7 on 2026-06-18 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0002_initial'),
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='ficha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fichas.fichatecnica'),
        ),
        migrations.AddField(
            model_name='configuracaoetiqueta',
            name='ficha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_etiqueta', to='fichas.fichatecnica'),
        ),
        migrations.AddField(
            model_name='ingredientefichatecnica',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento'),
        ),
        migrations.AddField(
            model_name='ingredientefichatecnica',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.fichatecnica'),
        ),
    ]
