# Generated by Django 6.0.4 on 2026-05-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_fichatecnica_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredientefichatecnica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personalizado', models.CharField(blank=True, max_length=255)),
                ('porcao', models.CharField(default='100g', max_length=50)),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('tamanho_etiqueta', models.CharField(default='medio', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_etiqueta', to='fichas.fichatecnica')),
            ],
        ),
    ]
