# Generated by Django 6.0.4 on 2026-05-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_alter_fichatecnica_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personalizado', models.CharField(blank=True, max_length=255)),
                ('tamanho_porcao', models.CharField(default='100g', max_length=50)),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('mostrar_sodio', models.BooleanField(default=True)),
                ('mostrar_acucar', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fichas.fichatecnica')),
            ],
        ),
    ]
