# Generated by Django 6.0.4 on 2026-04-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='número',
            new_name='numero',
        ),
    ]
