# Generated by Django 6.0.4 on 2026-06-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('energia_kcal', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor energético (kcal)')),
                ('carboidratos', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('acucares_totais', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Açúcares totais')),
                ('acucares_adicionados', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Açúcares adicionados')),
                ('proteinas', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Proteínas')),
                ('gorduras_totais', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('gorduras_saturadas', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('gorduras_trans', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fibra_alimentar', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Sódio')),
                ('minerais', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('vitaminas', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('contem_gluten', models.BooleanField(default=False)),
                ('contem_lactose', models.BooleanField(default=False)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_medida', models.CharField(blank=True, choices=[('g', 'gramas'), ('kg', 'quilograma'), ('ml', 'mililitro'), ('l', 'litro'), ('un', 'unidade')], max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'db_table': 'Alimento',
                'ordering': ['numero', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('porcoes', models.IntegerField(default=1)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Receita',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
            ],
        ),
    ]
