# Generated by Django 6.0.4 on 2026-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0003_alter_alimento_id_alter_ingredientereceita_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredientereceita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
