# Generated by Django 5.2.7 on 2026-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0003_alter_alimento_id_alter_ingredientereceita_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='minerais',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='vitaminas',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
