# Generated by Django 5.2.7 on 2026-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0004_alimento_minerais_alimento_vitaminas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='acucares_adicionados',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Açúcares adicionados'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='acucares_totais',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Açúcares totais'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia_kcal',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor energético (kcal)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Proteínas'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Sódio'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='vitaminas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
