# Generated by Django 5.2.7 on 2026-05-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0004_alter_alimento_id_alter_ingredientereceita_id_and_more'),
        ('alimentos', '0005_alter_alimento_acucares_adicionados_and_more'),
    ]

    operations = [
    ]
