# Generated by Django 5.2.7 on 2026-06-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0008_alter_alimento_id_alter_ingredientereceita_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='contem_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='contem_lactose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredientereceita',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
