# Generated by Django 5.2.7 on 2026-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='limite_receitas',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_usuarios',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plano',
            name='permite_exportacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_rotulo',
            field=models.IntegerField(default=5),
        ),
    ]
