# Generated by Django 5.2.7 on 2026-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_empresa_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='senha',
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.CharField(choices=[('gratis', 'Grátis'), ('profissional', 'Profissional'), ('empresarial', 'Empresarial')], default='gratis', max_length=20),
        ),
    ]
