# Generated by Django 5.2.7 on 2026-06-22 20:27

from django.db import migrations


def create_default_planos(apps, schema_editor):
    Plano = apps.get_model('usuarios', 'Plano')
    
    # Create or update Grátis
    Plano.objects.update_or_create(
        id=1,
        defaults={
            'nome': 'Grátis',
            'descricao': 'Para quem já vende e precisa de controle real',
            'preco': 0.00,
            'limite_receitas': 5,
            'limite_rotulo': 3,
            'limite_usuarios': 1,
            'permite_exportacao': False,
            'ativo': True
        }
    )
    
    # Create or update Profissional
    Plano.objects.update_or_create(
        id=2,
        defaults={
            'nome': 'Profissional',
            'descricao': 'Para negócios que precisam de rótulo e etiqueta prontos',
            'preco': 97.00,
            'limite_receitas': 60,
            'limite_rotulo': 999999,
            'limite_usuarios': 2,
            'permite_exportacao': True,
            'ativo': True
        }
    )
    
    # Create or update Empresarial (optional)
    Plano.objects.update_or_create(
        id=3,
        defaults={
            'nome': 'Empresarial',
            'descricao': 'Para grandes operações',
            'preco': 197.00,
            'limite_receitas': 5, # or whatever default
            'limite_rotulo': 999999,
            'limite_usuarios': 5,
            'permite_exportacao': True,
            'ativo': True
        }
    )

def reverse_default_planos(apps, schema_editor):
    Plano = apps.get_model('usuarios', 'Plano')
    Plano.objects.filter(id__in=[1, 2, 3]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_plano_limite_receitas_plano_limite_usuarios_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_planos, reverse_default_planos)
    ]
