# Generated by Django 5.2.7 on 2026-04-28 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_empresa_senha_empresa_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('cadastro', 'Cadastro'), ('receita', 'Receita'), ('rotulo', 'Rótulo'), ('ingrediente', 'Ingrediente'), ('plano', 'Plano')], max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
